// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {charsToken, unclearToken} from "../tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "(QOQOVOOOQOVO'#C_OQOVO'#C`OQOVO'#CaO!eOWO'#CbO!pOVO'#ClO#wOVO'#CmOOOR'#Co'#CoO$ROSO'#CpO!pOVO'#CqOOOR'#DX'#DXOOOR'#Cr'#CrO$WOSO'#CtO!pOVO'#CvOOOR'#Ch'#ChOOOR'#C|'#C|OOOR'#Cw'#CwQQOVOOO$`OVO,58yO$gOVO,58zO$nOVO,58{OQOVO,58|OQOVO,59OOQOVO,59QOOOR'#Cx'#CxO$uOVO,59WO$|OVO,59XOOOR,59X,59XO%WOSO,59XO%]OSO,59[O%bOVO,59]O%lOSO,59`O%qOVO,59bOOOR-E6u-E6uOOOR1G.e1G.eOOOR1G.f1G.fOOOR1G.g1G.gO%xOVO1G.hO&POVO1G.jO&WOVO1G.lOOOR-E6v-E6vOOOR1G.r1G.rOOOR1G.s1G.sO&_OSO1G.sOOOR1G.v1G.vOOOR1G.w1G.wO&dOSO1G.wOOOR1G.z1G.zOOOR1G.|1G.|OOOR7+$S7+$SOOOR7+$U7+$UOOOR7+$W7+$WOOOR7+$_7+$_OOOR7+$c7+$c",
  stateData: "&n~OP^O]^O^^O_^OgZOi^OnZOo[OqPOsQOuROvSOwTOyUO|VO}WO!PXO!QZO!RZO!SZO!U]O~OVeOXfOZgO~OP^O]^O^^O_^OgZOi^OnZOo[OwTOyUO|VO}WO!PXO!QZO!RZO!SZO!U]O~OblOzkO~P!pO_mO~O_oOgoO~OrrO~PQOtsO~PQOttO~PQOxyO~P!pOb{OzzO~P!pOzzO~O!O|O~Ob!OO!O}O~P!pO!T!PO~O!V!QO~P!pOt!RO~PQOt!SO~PQOt!TO~PQOz!UO~O!O!VO~OZ^_Z~",
  goto: "%_|PPP}}}}P}P}P!_PPP!y!yP#c#c#c!yP!yP!y#{$kPPP$}PPPPPPPPPP!ym_OPQRabcdefguvwl_OPQRabcdefguvwahTUX]ijnp}^OPQRTUX]abcdefgijnpuvw}YOPQRTUX]abcdefgijnpuvwQaOQbPQcQQdR^qabcduvwQueQvfRwgQiTQjUQnXQp]Xxijnpm`OPQRabcdefguvw",
  nodeNames: "⚠ Unclear Document Div Recto Verso Part PartId Fragment FragmentNum Column ColumnNum Inline LineBreakWrapped LineBreak Number Abbrev Supplied CertLow GapUnknown Gap SuppliedLost Text QuestionMark LostLines Illegible Erasure",
  maxTerm: 53,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "+y~Rapq!Wxy!]yz!p!O!P!u!Q![#v!^!_'v!_!`(y!`!a)f!a!b)k!c!}'^!}#O)p#P#Q*]#T#`'^#`#a*b#a#o'^&Fp&Fq+o&Fq&Fr+t~!]O!R~~!bPw~!a!b!e~!hPyz!k~!pOb~~!uOx~~!zQ!Q~!Q![#Q!a!b#n~#VQi~!Q![#Q#`#a#]~#`P#]#^#c~#fP#b#c#i~#nOi~~#sPi~#`#a#]~#{S_P!O!P$X!Q![#v!c!}'^#T#o'^~$^T^Ppq$m}!O$r#V#W%P#Y#Z%t#d#e&uP$rO^P~$wP]~pq$z~%PO]~Q%SP#c#d%VQ%YP#`#a%]Q%`P#i#j%cQ%fP#a#b%iQ%lP#b#c%oQ%tOZQ~%wP#f#g%z~%}P#T#U&Q~&TP#Z#[&W~&ZP#a#b&^~&aP#X#Y&d~&gP#b#c&j~&mP#h#i&p~&uOX~Q&xP#T#U&{Q'OP#f#g'RQ'UP#h#i'XQ'^OVQQ'aS!O!P'm!Q!['^!c!}'^#T#o'^Q'pQ#V#W%P#d#e&u~'{Qy~!_!`(R!f!g(W~(WOq~~(ZP!_!`(^~(aP!O!P(d~(iQv~#f#g(o#j#k(t~(tOs~~(yOu~~)OQ!S~!`!a)U!f!g)Z~)ZOr~~)^P!`!a)a~)fOt~~)kOz~~)pOg~~)uP!P~!O!P)x~)}P}~!a!b*Q~*TP#P#Q*W~*]O|~~*bO!O~R*eU!O!P'm!Q!['^!c!}'^#T#]'^#]#^*w#^#o'^R*zU!O!P'm!Q!['^!c!}'^#T#b'^#b#c+^#c#o'^R+cS!TP!O!P'm!Q!['^!c!}'^#T#o'^~+tO!U~~+yO!V~",
  tokenizers: [charsToken, unclearToken, 0, 1],
  topRules: {"Document":[0,2]},
  tokenPrec: 255
})
