// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {leidenCharsOrAbbreviation, leidenExpan} from "../tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!QOQOROOOcOSO'#C`OOOQ'#Ca'#CaOOOQ'#Ce'#CeOOOQ'#Cb'#CbQQOROOOOOQ,58z,58zOOOQ-E6`-E6`",
  stateData: "h~OPPOWQOYQOZQO[QO~OQUO~O",
  goto: "iYPPPPZZ_PPeTROTQTORVTTSOT",
  nodeNames: "⚠ Abbreviation Expan Document Abbrev Text",
  maxTerm: 12,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "k~RR!O!P[!_!`a!a!bf~aOY~~fO[~~kOZ~",
  tokenizers: [0, leidenCharsOrAbbreviation, leidenExpan],
  topRules: {"Document":[0,3]},
  tokenPrec: 0
})
