// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&xOQOPOOOQOPO'#C^OQOPO'#C_OQOPO'#C`O!bOQO'#CaO!jOPO'#ChO#nOPO'#CiOOOO'#Ck'#CkO#xOPO'#ClO!jOPO'#CmOOOO'#DS'#DSOOOO'#Cn'#CnOOOO'#C}'#C}OOOO'#Cv'#CvOOOO'#Cs'#CsQQOPOOO#}OPO,58xO$UOPO,58yO$]OPO,58zOQOPO,58{OQOPO,58}OOOO'#Ct'#CtO$dOPO,59SO$kOPO,59TOOOO,59T,59TO$uOPO,59TO$zOPO,59WO%POPO,59XOOOO-E6q-E6qOOOO1G.d1G.dOOOO1G.e1G.eOOOO1G.f1G.fO%ZOPO1G.gO%bOPO1G.iOOOO-E6r-E6rOOOO1G.n1G.nOOOO1G.o1G.oO%iOPO1G.oOOOO1G.r1G.rOOOO1G.s1G.sO%nOPO1G.sOOOO7+$R7+$ROOOO7+$T7+$TOOOO7+$Z7+$ZOOOO7+$_7+$_",
  stateData: "%w~OX[OY[OZ[OcZOd[Oe[Of[OkPOmQOoROpSOrTOtUOwVOxWOzXO{ZO|ZO}ZO!OZO~OUcOWdO~OX[OY[OZ[OcZOd[Oe[Of[OrTOtUOwVOxWOzXO{ZO|ZO}ZO!OZO~O^iOuhO~P!jOZjO~OlmO~PQOnnO~PQOnoO~PQOssO~P!jO^uOutO~P!jOutO~OyvO~O^xOywO~P!jOnyO~PQOnzO~PQOu{O~Oy|O~OYZ{~",
  goto: "$pwPPxxxxPxPPPP!W!WP!l!l!l!WPPPP#Q#lP#zPPPPPP$YPPPP!Wi]OPQR_`abcdpqu[OPQRTUX_`abcdfgkpquYOPQRTUX_`abcdfgkpqQ_OQ`PQaQQbR[l_`abpqQpcRqdQfTQgUQkXVrfgki^OPQR_`abcdpqh]OPQR_`abcdpq]eTUXfgk",
  nodeNames: "⚠ Document Div Recto Verso Part PartId Fragment FragmentNum LineBreakWrapped LineBreak Number Abbrev Supplied CertLow GapUnknown Gap SuppliedLost Text QuestionMark Illegible Unclear LostLines",
  maxTerm: 46,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "5i~RjOp!spq%tqx!sxy%|yz&dz!O!s!O!P&l!P!Q!s!Q!['p![!^!s!^!_+Z!_!`,a!`!a-P!a!b-X!b!c!s!c!}-a!}#O/c#O#P!s#P#Q0R#Q#T!s#T#`-a#`#a0Z#a#o-a#o2e!s2e2f#h2f~!s~!xY{POp#hqx#hz!O#h!P!Q#h![!^#h!b!}#h#O#P#h#Q2e#h2e2f$V2f~#hP#mW{POp#hqx#hz!O#h!P!Q#h![!^#h!b!}#h#O#P#h#Q~#h~$^ae~{POp!spq%cqx!sxz%cz!O!s!O!P%c!P!Q!s!Q![%c![!^!s!^!b%c!b!}!s!}#O%c#O#P!s#P#Q%c#Q2e!s2e2f#h2f~!s~%fP2e2f%i~%nQe~O2e%c2f~%c~%yP}~2e2f%i~&RQr~!a!b&X2e2f%i~&[Pyz&_~&dO^~~&iPs~2e2f%i~&qR|~!Q![&z!a!b'h2e2f%i~'PQd~!Q![&z#`#a'V~'YP#]#^']~'`P#b#c'c~'hOd~~'mPd~#`#a'V~'uTZP!O!P(U!Q![*c!c!}*t#T#o*t2e2f%i~(ZSYPpq(g}!O(l#Y#Z(y#d#e)zP(lOYP~(qPX~pq(t~(yOX~~(|P#f#g)P~)SP#T#U)V~)YP#Z#[)]~)`P#a#b)c~)fP#X#Y)i~)lP#b#c)o~)rP#h#i)u~)zOW~Q)}P#T#U*QQ*TP#f#g*WQ*ZP#h#i*^Q*cOUQ~*hSZP!O!P(U!Q![*c!c!}*t#T#o*tQ*wS!O!P+T!Q![*t!c!}*t#T#o*tQ+WP#d#e)z~+`Rt~!_!`+i!f!g+n2e2f%i~+nOk~~+qP!_!`+t~+wP!O!P+z~,PQp~#f#g,V#j#k,[~,[Om~~,aOo~~,fR!O~!`!a,o!f!g,t2e2f%i~,tOl~~,wP!`!a,z~-POn~~-UPu~2e2f%i~-^Pc~2e2f%i~-f_{POp#hqx#hz!O#h!O!P+T!P!Q#h!Q![*t![!^#h!b!c#h!c!}.e#O#P#h#Q#T#h#T#o.e#o2e#h2e2f$V2f~#hR.j]{POp#hqx#hz!O#h!O!P+T!P!Q#h!Q![*t![!^#h!b!c#h!c!}.e#O#P#h#Q#T#h#T#o.e#o~#h~/hQz~!O!P/n2e2f%i~/sPx~!a!b/v~/yP#P#Q/|~0ROw~~0WPy~2e2f%i~0`a{POp#hqx#hz!O#h!O!P+T!P!Q#h!Q![*t![!^#h!b!c#h!c!}.e#O#P#h#Q#T#h#T#c.e#c#d1e#d#o.e#o2e#h2e2f$V2f~#h~1j_{POp#hqx#hz!O#h!O!P+T!P!Q#h!Q![*t![!^#h!b!c#h!c!}.e#O#P#h#Q#T#h#T#g.e#g#h2i#h#o.e#o~#h~2n_{POp#hqx#hz!O#h!O!P+T!P!Q#h!Q![*t![!^#h!b!c#h!c!}.e#O#P#h#Q#T#h#T#h.e#h#i3m#i#o.e#o~#h~3r]{POp#hqx#hz!O#h!O!P4k!P!Q#h!Q![*t![!^#h!b!c#h!c!}.e#O#P#h#Q#T#h#T#o.e#o~#h~4nR!Q![4w!a!b5c#d#e)z~4zQ!Q![4w#`#a5Q~5TP#]#^5W~5ZP#b#c5^~5cOf~~5fP#`#a5Q",
  tokenizers: [0, 1],
  topRules: {"Document":[0,1]},
  tokenPrec: 219
})
