// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Document = 1,
  Number = 5,
  Abbrev = 6,
  Supplied = 7,
  CertLow = 8,
  Text = 11,
  QuestionMark = 12
