// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Document = 1,
  PartId = 6,
  FragmentNum = 8,
  LineBreakWrapped = 9,
  LineBreak = 10,
  Number = 11,
  Abbrev = 12,
  Supplied = 13,
  CertLow = 14,
  Text = 18,
  QuestionMark = 19,
  Illegible = 20,
  Unclear = 21,
  LostLines = 22
