// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  chars = 27,
  lostLinesStart = 28,
  Unclear = 1,
  Document = 2,
  PartId = 7,
  FragmentNum = 9,
  LineBreakWrapped = 10,
  LineBreak = 11,
  Number = 12,
  Abbrev = 13,
  Supplied = 14,
  CertLow = 15,
  Text = 19,
  QuestionMark = 20,
  LostLines = 21,
  Illegible = 22,
  Erasure = 23
