// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {leidenHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'tOoOPOOOvOPO'#C^O}OPO'#C_OOOO'#Co'#CoO!UOPO'#CbO!mOPO'#CcO!wOPO'#CeO!UOPO'#CfOOOO'#C{'#C{OOOO'#Cv'#CvO!|OPO'#CvOOOO'#Cl'#ClO#nOPO'#CjOOOO'#Ct'#CtOOOO'#Ck'#CkQQOPOOOQOPOOO#uOPO,58xOQOPO,58xO#|OPO,58yOQOPO,58yO$TOPO,58|OOOO,58},58}O$[OPO,58}O$aOPO,58}O$kOPO,59PO$pOPO,59QO!UOPO,58zO!UOPO,59TOOOO-E6j-E6jOOOO,59U,59UOOOO-E6i-E6iO$wOPO1G.dO%rOPO1G.dO%yOPO1G.eO&tOPO1G.eOOOO1G.h1G.hOOOO1G.i1G.iO&{OPO1G.iOOOO1G.k1G.kOOOO1G.l1G.lO'QOPO1G.fO'XOPO1G.oOOOO7+$O7+$OO'`OPO7+$OOOOO7+$P7+$PO(ZOPO7+$POOOO7+$T7+$TOOOO7+$Q7+$QOOOO7+$Z7+$ZOOOO<<Gj<<GjOOOO<<Gk<<Gk",
  stateData: ")U~OTYOZXO[XOdPOfQOkSOmTOpUOrVO~Ob`O~PQObbO~PQObdO~PQOTXOZXO[XOkSOmTOpUOrVO~OWgOnfO~P!UOTiO~OikOslOTjXZjX[jXbjXkjXmjXpjXrjX~ObnO~P!UOepO~PQOgrO~PQOltO~P!UOnuO~OWvOnuO~P!UOqwO~OqxO~P!UOb{OTQiZQi[QiaQidQifQikQimQipQirQieQigQi~Oe|O~PQOb}OTRiZRi[RiaRidRifRikRimRipRirRieRigRi~Og!OO~PQOn!PO~Ob!QO~P!UOb!RO~P!UOb!SOTQqZQq[QqaQqdQqfQqkQqmQqpQqrQqeQqgQq~Ob!TOTRqZRq[RqaRqdRqfRqkRqmRqpRqrRqeRqgRq~O",
  goto: "%cpPPqq!OP!]!]P!u!uPP!O!O#_#vPP$lPPPP$lP$yPPPP!]gROPQ_`abcdqsg]OPQ_`abcdqs}XOPQSTV[_`abcdehjklqsyz}WOPQSTV[_`abcdehjklqsyzS_O`QaPQcQYo_acqsQqbRsdf[OPQ_`abcdqsQeSQhTQjV[m[ehjyzQykRzlg^OPQ_`abcdqs}ZOPQSTV[_`abcdehjklqsyz",
  nodeNames: "⚠ Document Div Recto NumberedWrappedLine Number Abbrev Supplied CertLow Gap SuppliedLost Text QuestionMark NumberedLine Line",
  maxTerm: 35,
  propSources: [leidenHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "&`~RcOY!^YZ!{Zx!^xy#Tyz#hz!O!^!O!P#m!P!Q!^!Q![$W![!^!^!^!_$`!_!`%X!`!a%r!a!b%w!b!}!^!}#O%|#O#P!^#P#Q&Z#Q~!^~!cWZ~OY!^Zx!^z!O!^!P!Q!^![!^!^!b!}!^#O#P!^#Q~!^~#QPb~YZ!{~#YPk~!a!b#]~#`Pyz#c~#hOW~~#mOl~~#pQpq#v}!O#{~#{Os~~$OPpq$R~$WOi~~$]PT~!Q![$W~$eQm~!_!`$k!f!g$p~$pOd~~$sP!_!`$v~$yP!O!P$|~%PP#f#g%S~%XOf~~%[Q!`!a%b!f!g%g~%gOe~~%jP!`!a%m~%rOg~~%wOn~~%|O[~~&RPr~!O!P&U~&ZOp~~&`Oq~",
  tokenizers: [0],
  topRules: {"Document":[0,1]},
  tokenPrec: 0
})
