// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {charsToken, unclearToken} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'nOQOVOOOQOVO'#C_OQOVO'#C`OQOVO'#CaO!eOWO'#CbO!mOVO'#CjO#tOVO'#CkOOOR'#Cm'#CmO$OOSO'#CnO!mOVO'#CoOOOR'#DV'#DVOOOR'#Cp'#CpO$TOSO'#CrO!mOVO'#CtOOOR'#Cf'#CfOOOR'#Cz'#CzOOOR'#Cu'#CuQQOVOOO$]OVO,58yO$dOVO,58zO$kOVO,58{OQOVO,58|OQOVO,59OOOOR'#Cv'#CvO$rOVO,59UO$yOVO,59VOOOR,59V,59VO%TOSO,59VO%YOSO,59YO%_OVO,59ZO%iOSO,59^O%nOVO,59`OOOR-E6s-E6sOOOR1G.e1G.eOOOR1G.f1G.fOOOR1G.g1G.gO%uOVO1G.hO%|OVO1G.jOOOR-E6t-E6tOOOR1G.p1G.pOOOR1G.q1G.qO&TOSO1G.qOOOR1G.t1G.tOOOR1G.u1G.uO&YOSO1G.uOOOR1G.x1G.xOOOR1G.z1G.zOOOR7+$S7+$SOOOR7+$U7+$UOOOR7+$]7+$]OOOR7+$a7+$a",
  stateData: "&b~OP^OZ^O[^O]^OeZOg^OlZOm[OoPOqQOsROtSOuTOwUOzVO{WO}XO!OZO!PZO!QZO!S]O~OVeOXfO~OP^OZ^O[^O]^OeZOg^OlZOm[OuTOwUOzVO{WO}XO!OZO!PZO!QZO!S]O~O`kOxjO~P!mO]lO~O]nOenO~OpqO~PQOrrO~PQOrsO~PQOvwO~P!mO`yOxxO~P!mOxxO~O|zO~O`|O|{O~P!mO!R}O~O!T!OO~P!mOr!PO~PQOr!QO~PQOx!RO~O|!SO~O[]~",
  goto: "$}zPPP{{{{P{P!ZPPP!s!sP#Z#Z#Z!sP!sP!s#q$]PPP$oPPPPPPPPPP!si_OPQRabcdeftuh_OPQRabcdeftuagTUX]himoy^OPQRTUX]abcdefhimotuyYOPQRTUX]abcdefhimotuQaOQbPQcQQdR[pabcdtuQteRufQhTQiUQmXQo]Xvhimoi`OPQRabcdeftu",
  nodeNames: "⚠ Unclear Document Div Recto Verso Part PartId Fragment FragmentNum Inline LineBreakWrapped LineBreak Number Abbrev Supplied CertLow GapUnknown Gap SuppliedLost Text QuestionMark LostLines Illegible Erasure",
  maxTerm: 51,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "+O~Rapq!Wxy!]yz!p!O!P!u!Q![#v!^!_&{!_!`(O!`!a(k!a!b(p!c!}&f!}#O(u#P#Q)b#T#`&f#`#a)g#a#o&f&Fp&Fq*t&Fq&Fr*y~!]O!P~~!bPu~!a!b!e~!hPyz!k~!pO`~~!uOv~~!zQ!O~!Q![#Q!a!b#n~#VQg~!Q![#Q#`#a#]~#`P#]#^#c~#fP#b#c#i~#nOg~~#sPg~#`#a#]~#{S]P!O!P$X!Q![#v!c!}&f#T#o&f~$^S[Ppq$j}!O$o#Y#Z$|#d#e%}P$oO[P~$tPZ~pq$w~$|OZ~~%PP#f#g%S~%VP#T#U%Y~%]P#Z#[%`~%cP#a#b%f~%iP#X#Y%l~%oP#b#c%r~%uP#h#i%x~%}OX~Q&QP#T#U&TQ&WP#f#g&ZQ&^P#h#i&aQ&fOVQQ&iS!O!P&u!Q![&f!c!}&f#T#o&fQ&xP#d#e%}~'QQw~!_!`'W!f!g']~']Oo~~'`P!_!`'c~'fP!O!P'i~'nQt~#f#g't#j#k'y~'yOq~~(OOs~~(TQ!Q~!`!a(Z!f!g(`~(`Op~~(cP!`!a(f~(kOr~~(pOx~~(uOe~~(zP}~!O!P(}~)SP{~!a!b)V~)YP#P#Q)]~)bOz~~)gO|~R)jU!O!P&u!Q![&f!c!}&f#T#]&f#]#^)|#^#o&fR*PU!O!P&u!Q![&f!c!}&f#T#b&f#b#c*c#c#o&fR*hS!RP!O!P&u!Q![&f!c!}&f#T#o&f~*yO!S~~+OO!T~",
  tokenizers: [charsToken, unclearToken, 0, 1],
  topRules: {"Document":[0,2]},
  tokenPrec: 245
})
